# Gradle
org.gradle.jvmargs=-Xmx2G
# Enable Gradle build cache
org.gradle.caching=true
# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# Project metadata
group=dev.tophatcat.mysteriouslands
mod_id=mysteriouslands
mod_description=A mod made during SpookyJam 2017, Mysterious Lands is a bundle of some spooky and miscellaneous nice to have biomes and content to enhance your Minecraft gameplay!
mod_display_name=Mysterious Lands
sources_url=https://github.com/kiris-mods/mysterious-lands
issues_url=https://github.com/kiris-mods/mysterious-lands/issues
license_url=https://github.com/kiris-mods/mysterious-lands/blob/dev/LICENSE.md
discord_url=https://discord.tophatcat.dev

curseforge_id=280003
modrinth_id=SrAIvfzS
