modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-2.1"
issueTrackerURL = "${issues_url}"
sourcesUrl = "${sources_url}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_display_name}"
displayURL = "${homepage_url}"
iconFile = "icon.png"
#credits = "" #Optional
authors = "KiriCattus"
description = '''${mod_description}'''

[dependencies]
"${mod_id}" = [
  { modId = "neoforge", type = "required", versionRange = "*", ordering = "NONE", side = "BOTH" },
  { modId = "minecraft", type = "required", versionRange = "[${minecraft_version}]", ordering = "NONE", side = "BOTH" },
  { modId = "sparkweave", type = "required", mc-publish = { curseforge = "911456", modrinth = "nf68xfAw" } },
  { modId = "${mod_id}", type = "required", versionRange = "[${version}]", ordering = "NONE", side = "BOTH" },
  { modId = "resourcefulconfig", mc-publish = { curseforge = "714059", modrinth = "M1953qlQ" } },
]

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
[features.${mod_id}]
#openGLVersion="[3.2,)"
javaVersion = "[${java_version},)"

[mc-publish]
curseforge = "curseforge_id"
modrinth = "modrinth_id"
loaders = ["neoforge"]
